version: '3.8'

services:
  files:
    build: .
    container_name: lumio_files_service
    ports:
      - '3001:3001'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672
      - NODE_ENV=development
    networks:
      - lumio_network

networks:
  lumio_network:
    external: true
    name: lumio_network
