apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: PORT
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: REFRESH_TOKEN_SECRET
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: RECAPTCHA_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: DATABASE_URL
            - name: IS_SWAGGER_ENABLED
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: IS_SWAGGER_ENABLED
            - name: INCLUDE_TESTING_MODULE
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: INCLUDE_TESTING_MODULE
            - name: SMTP_FROM_GMAIL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: SMTP_FROM_GMAIL
            - name: ACCESS_TOKEN_EXPIRE_IN
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: ACCESS_TOKEN_EXPIRE_IN
            - name: REFRESH_TOKEN_EXPIRE_IN
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: REFRESH_TOKEN_EXPIRE_IN
            - name: THROTTLER_TTL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: THROTTLER_TTL
            - name: THROTTLER_LIMIT
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: THROTTLER_LIMIT
            - name: SMPT_COM_PASS
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: SMPT_COM_PASS
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: SMTP_PORT
            - name: SMTP_SECURE
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: SMTP_SECURE
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: FRONTEND_URL
            - name: YANDEX_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: YANDEX_CLIENT_ID
            - name: YANDEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: YANDEX_CLIENT_SECRET
            - name: YANDEX_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: YANDEX_CALLBACK_URL
            - name: FILES_FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: FILES_FRONTEND_URL
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: INTERNAL_API_KEY
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: NODE_ENV
            - name: RMQ_URL
              valueFrom:
                secretKeyRef:
                  name: lumio-back-end-production-config-secret
                  key: RMQ_URL
